name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: 	ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: env
      # Set the Project Env Packages
      run: |
        sudo apt install cmake ninja-build
        sudo apt-get install git perl python3 make autoconf g++ flex bison ccache
        sudo apt-get install libgoogle-perftools-dev numactl
        sudo apt-get install libfl2
        sudo apt-get install libfl-dev
        sudo apt-get install zlibc zlib1g zlib1g-dev

    - name: Install Verilator
      run: |
        git clone https://github.com/verilator/verilator
        unset VERILATOR_ROOT
        cd verilator
        git pull
        git checkout v5.004
        autoconf
        ./configure
        make -j `nproc`
        sudo make install

    - name: Initialize 3rdparty
      run: git submodule --init --recursive

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

